# ===============================
# APP CONFIGURATION
# ===============================
spring.application.name=rh_rse
server.port=8081

# ===============================
# MONGODB CONFIGURATION (ATLAS)
# ===============================
spring.data.mongodb.uri=mongodb+srv://ranimkhemire_db_user:BE18ybH01yWWUfAd@hr-platform.u9vgngd.mongodb.net/hr-platform?appName=hr-platform
spring.data.mongodb.database=hr-platform

# MongoDB LOCAL (Commenté - Pour utiliser en local, décommentez ceci et commentez Atlas en haut)
# spring.data.mongodb.host=localhost
# spring.data.mongodb.port=27017
# spring.data.mongodb.database=hr-platform

# ===============================
# JWT CONFIGURATION
# ===============================
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# ===============================
# MULTIPART & UPLOAD DE FICHIERS
# ===============================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
#server.tomcat.max-http-post-size=10000000

# ===============================
# GOOGLE API
# ===============================
google.credentials.path=src/main/resources/google-credentials.json
google.calendar.timezone=Africa/Tunis

# ===============================
# EMAIL CONFIGURATION (GMAIL)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=doniabouzouita2@gmail.com
spring.mail.password=ghixxpymafevtaxg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ===============================
# FRONTEND URL
# ===============================
app.frontend.url=http://192.168.1.102:4200
