spring.application.name=rh_rse

# MongoDB
spring.data.mongodb.uri=mongodb+srv://mon_user_test:MonMotDePasseTest123%21@pi.uioai9u.mongodb.net/?appName=pi
spring.data.mongodb.database=pi
# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

server.port=8081



#spring.application.name=rh_rse
#
## MongoDB LOCAL
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=hr-platform
#
## JWT
#jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#jwt.expiration=86400000
#
#server.port=8081