spring.application.name=rh_rse

# MongoDB
spring.data.mongodb.uri=mongodb+srv://mon_user_test:MonMotDePasseTest123%21@pi.uioai9u.mongodb.net/?appName=pi
spring.data.mongodb.database=pi
# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

server.port=8081

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lindajenhani58@gmail.com
spring.mail.password=svvfprtxrnorfxmi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#spring.application.name=rh_rse
#
## MongoDB LOCAL
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=hr-platform
#
## JWT
#jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#jwt.expiration=86400000
#
#server.port=8081

logging.level.org.springframework.web=DEBUG
logging.level.tn.esprit.rh_rse=DEBUG
logging.level.org.springframework.security=DEBUG


# File upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload-dir=./uploads/conges/


# Hugging Face API
huggingface.api.url=https://api-inference.huggingface.co/models/
huggingface.api.key=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